### ISSUE TITLE
Issue with the Float Lib

### ISSUE THREAD

**Issue by 8bit-Dude** [mrdudz/cc65-floatlib#1]
Hello There!

Thank you very much for making this very useful library.
I can build the library and testcode (using latest cc65), though I get the following message:

`float.s(169): Warning: Didn't use zeropage addressing for 'sreg'`

When running the testcode, the floats do not seem to work properly. 
The function f1() crashes the application, and the following code shows a:0:

`a=itof(2);
printf("a:%x\n",a);`

Any help would be most appreciated!!!
Anthony

**Comment by mrdudz** [comment]
i haven't looked at this lib for a long time... so not sure if i can help :) 

what happens with the itof is that the functions expects a "float" as input, ie an "unsigned long" in IEE float format - it does not work with regular (human readable) literals. the same way when a "float" is returned, it will be returned as an "unsigned long" which is again in IEE format.
what you see in the printf is simply the lower two bytes of the resulting number, which happen to be 0.

**Comment by 8bit-Dude** [comment]
Thank you so much for picking up this question.
I am trying to read floats from a binary file, which cc65 does not support, and convert them to fixed point.
Would you have any tips on how I could achieve that using the cc65-floatlib?
Thanks in advance!

**Comment by 8bit-Dude** [comment]
I managed to figure this out myself, and wrote a small file to convert floats (char buffer) into 8.8 fixed point.
See here: https://github.com/MohicanFr/C64-Studio/blob/master/include/cc65-libfix8.h

**Comment by mrdudz** [comment]
the original issue is solved in head
