### ISSUE TITLE
Please provide a licence for the code

### ISSUE THREAD

**Issue by elderling** [mrdudz/cc65-floatlib#4]
There's no licence for the code so I'm afraid to use it.

**Comment by mrdudz** [comment]
there, have fun :)

**Comment by elderling** [comment]
Thank you for adding the license & writing the code!

**Comment by mrdudz** [comment]
Let me know when you made something useful out of it :)

**Comment by elderling** [comment]
First I need to get it working for the VIC-20!

**Comment by mrdudz** [comment]
Oh that sounds interesting, feel free to provide patches :) It shouldnt be too hard, i think, the kernal and BASIC is very similar
